import { createClient } from '@supabase/supabase-js';
import { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY } from '$env/static/public';
import type { Database } from './database.types';

// The single Supabase entry point for the whole app, typed against the real
// database schema (database.types.ts, generated by `supabase gen types`). Every
// table read/write and RPC is now checked at compile time — the safety net that
// makes the "wage silently zeroed" class of bug impossible to ship.
if (
  !PUBLIC_SUPABASE_URL ||
  !PUBLIC_SUPABASE_ANON_KEY ||
  PUBLIC_SUPABASE_URL.includes('your-project') ||
  PUBLIC_SUPABASE_ANON_KEY.includes('your-publishable-key')
) {
  throw new Error(
    'Supabase is not configured. Set PUBLIC_SUPABASE_URL and PUBLIC_SUPABASE_ANON_KEY.'
  );
}

export const supabase = createClient<Database>(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY);
